### ISSUE TITLE
npm Organisation

### ISSUE THREAD

**Issue by fabianmoronzirfas** [ExtendScript/extendscript-es5-shim#1]
@EugenTepin I wrote to the npm support. Let's see if they have some kind of org plan for open source projects only.

**Comment by EugenTepin** [comment]
_This discussion moved here from this [issue](https://github.com/EugenTepin/ps-scripting-es5shim/issues/1)_

**Comment by EugenTepin** [comment]
@fabianmoronzirfas  as for your questions:
> We just need some build script to concat them all.

I suggest webpack for that purpose.

> Should we make a fork of your repo or just copy over the sources?

I do not know what is better, i have zero experience in that kind of questions. But i prefer to keep my repo and commit into it.

**Comment by fabianmoronzirfas** [comment]
Got a reply from npm support.  

>At this time, we do not have a free organization option. However, this is something we are seriously considering/exploring, although I can't tell you when it may be available.  
>In the meantime, what I'd suggest is creating a username for your company/organization and publishing scoped, public packages to that account. You can easily add collaborators to these packages, and then if free orgs becomes available we can look at upgrading your free user account to a free org account.  
>Let me know if you have more questions, I'll be happy to help.  

So I would go ahead and create a extendscript user account and later on we can create a shared account from that.

**Comment by EugenTepin** [comment]
Ok, i will check what are the "scoped, public packages", and how to use them.

**Comment by fabianmoronzirfas** [comment]
Got the account https://www.npmjs.com/~extendscript
