### ISSUE TITLE
Empty section for Usage 

### ISSUE THREAD

**Issue by lumenn** [ExtendScript/extendscript-es5-shim#12]
Hey, i'm trying to use this package, but i'm failing on building part.

It would be nice to have some tips in the **Usage** section of the ```readme.md``` file.

In [extendscriptr](https://github.com/ExtendScript/extendscriptr) it's clear how to build something with it. 
``` extendscriptr --script src/scripts/helloWorld.js --output dist/helloWord.js ``` just clarify everything.

But here i'm just stuck. (I'd rather use those shims, than the extendscriptr, as for this one repo there is a fork with typescript definitions)

Also wondering if extendscriptr could use those shims?

**Comment by fabianmoronzirfas** [comment]
Yes it should use these https://github.com/ExtendScript/extendscriptr/issues/24 
You just need to include them like 

```js
//@include path/to/bundle.js
```
