### ISSUE TITLE
Republish npm script?

### ISSUE THREAD

**Issue by sbrown345** [ExtendScript/extendscript-es5-shim#19]
The last publish was 8 months ago and there's been a lot of commits since then including the typescript definitions.

**Comment by fabianmoronzirfas** [comment]
Hi @sbrown345 There is currently an issue with the types. See #18 I would love to revert them back to the original ones and therefore make #17 work (building a Extendscript testing suite that is interchangeable with Jest). This would give us a little more confidence for this repo that everything is working as it should.

So help on #18 is welcome. I currently don't have the time to work on this. Also after I saw this project https://github.com/ten-A/Types-for-Adobe I actually feel that maintaining the shims manually should be deprecated and there should go more effort in making Typescript transpilation work then maintaning these shims.

Anyway if you are willing to work on #18 maybe I get the drive to put some effort into #17 again 😉

**Comment by sbrown345** [comment]
Thanks for the info @fabianmoronzirfas 

I'm using the ten-A/Types-for-Adobe already, I've done a small change in PR #20.

I've got it working well enough for my use now, I forked it and removed the re-declarations and installed the github repo directly in npm.
