### ISSUE TITLE
Object.create() does not use `value` properly

### ISSUE THREAD

**Issue by toddfast** [ExtendScript/extendscript-es5-shim#26]
[Line 41](https://github.com/ExtendScript/extendscript-es5-shim/blob/cdbf0d86c1aff9dc551d7be3f2dd407919ee0d84/Object/create.js#L42) in `Object.create()` I believe should be `obj[prop] = Properties[prop].value;`.

There is a check for the `value` property on line 41 but the property is not used on line 42 as expected. As a result, this shim doesn't work as expected compared to either Chrome or [this shim](https://gist.github.com/roboticstone/bf537252607286aa8ef6). You can see a [test case here](https://gist.github.com/toddfast/0cbbbc4639226ef004b96d07aec9f172). That code fails with "Error 24: Object is not a function." in Illustrator 2020 (24.3) using this polyfill.

**Comment by fabianmoronzirfas** [comment]
Thanks for the bug report @toddfast this repo is somewhat unmaintained. Would you be open to write a PR that fixes that problem?

**Comment by toddfast** [comment]
Hi Fabian, see pull request above ^^^

**Comment by fabianmoronzirfas** [comment]
Thanks. Publish 0.3.1 with your fix.
