### ISSUE TITLE
Submit to npm?

### ISSUE THREAD

**Issue by andyinabox** [ExtendScript/extendscript-es5-shim#5]
Looks like there isn't yet an npm package for this tool. Just curious, any reason it hasn't been submitted yet? Would be happy to help get this ready to put out in the wild if there's anything I can do.

Also, I'm eager to help incorporate this into Extendscriptr to resolve https://github.com/ExtendScript/extendscriptr/issues/24

**Comment by fabianmoronzirfas** [comment]
Yes there is https://www.npmjs.com/package/extendscriptr.

**Comment by fabianmoronzirfas** [comment]
Hi @andyinabox I added you to the shim and the extendscriptr team. Great you got the time and will to work on this 👍  🚀
