### ISSUE TITLE
publish as npm package?

### ISSUE THREAD

**Issue by BenZed** [ExtendScript/extendscript-es5-shim#7]
Can this repo be published as an npm package?

I'm rewriting my [after effects package](https://www.npmjs.com/package/after-effects) which involves an es5 shim, and I'd like to reference this one.

I could also publish it myself, and point it toward this repo, if there are no objections.

**Comment by fabianmoronzirfas** [comment]
Done. https://www.npmjs.com/package/extendscript-es5-shim

**Comment by BenZed** [comment]
Awesome, thanks! :)
