### ISSUE TITLE
re-bundle and publish latest

### ISSUE THREAD

**Issue by tracker1** [ExtendScript/extendscript-es5-shim#9]
Should re-run the bundle, version a point release, and publish the update to npm.

**Comment by EugenTepin** [comment]
@fabianmoronzirfas version on npm is **0.1.3**, but here in package.json version is **0.1.2**, did you rebuild npm package after my fix? Or it is something else?

**Comment by fabianmoronzirfas** [comment]
Good question. I really can't remember.

**Comment by fabianmoronzirfas** [comment]
I got locally the 0.1.3. I guess I re-bundled, bumped a version and did not push it again. Sorry.

**Comment by fabianmoronzirfas** [comment]
repo and npm registry are are re-aligned
